language: python
python:
  - "2.7"
install:
  - pip install $DJANGO
script:
  - python runtests.py
env:
  - DJANGO="Django==1.4.22"
  - DJANGO="Django==1.5.12"
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.11"
